name: ai-news-cron

on:
  schedule:
    - cron: "*/2 * * * *"  # каждые 2 минуты
  workflow_dispatch: {}

permissions:
  contents: write  # чтобы коммитить обновлённые data/*.json

concurrency:
  group: ai-news-cron
  cancel-in-progress: true

jobs:
  run-on-schedule:
    runs-on: ubuntu-latest
    environment: TELEGRAM_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Prepare data directory
        run: |
          mkdir -p data
          [ -f data/published.json ] || echo "[]" > data/published.json
          [ -f data/recent_titles.json ] || echo "[]" > data/recent_titles.json

      - name: Create .env from secrets/vars
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          DISABLE_OPENAI: ${{ secrets.DISABLE_OPENAI }}
          RSS_FEEDS: ${{ vars.RSS_FEEDS }}
        run: |
          cat > .env <<EOF
          TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
          CHAT_ID=${CHAT_ID}
          OPENAI_API_KEY=${OPENAI_API_KEY}
          LLM_PROVIDER=${LLM_PROVIDER:-openai}
          MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
          DISABLE_OPENAI=${DISABLE_OPENAI:-0}
          RSS_FEEDS=${RSS_FEEDS}
          CHECK_INTERVAL_MIN=15
          MAX_POSTS_PER_CYCLE=1
          POST_DELAY_SEC=2
          RECENT_TITLES_MAX=300
          RUN_ONCE=1
          EOF

      - name: Run bot every 2 minutes (5 iterations)
        env:
          ITERATIONS: 5
          SLEEP_SEC: 120
        run: |
          i=1
          while [ "$i" -le "${ITERATIONS}" ]; do
            echo "[AI-NEWS] Iteration $i/${ITERATIONS}"
            python -u bot.py || true
            if [ "$i" -lt "${ITERATIONS}" ]; then
              echo "Sleeping ${SLEEP_SEC}s..."
              sleep "${SLEEP_SEC}"
            fi
            i=$((i+1))
          done

      - name: Commit data changes (published/titles)
        run: |
          if ! git diff --quiet -- data; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/published.json data/recent_titles.json
            git commit -m "chore(data): update published and titles [skip ci]"
            git push
          fi


